public class class338 {
   public static String field3891;
   public static String field3892;
   public static String field3893 = "Drop";
   public static String field3894 = "Hidden";
   public static String field3895 = "Ok";
   public static String field3896 = "Select";
   public static String field3897 = "Continue";
   public static String field3898;
   public static String field3899 = "null";
   public static String field3900 = "Trust this computer";
   public static String field3901;
   public static String field3902 = "Loading - please wait.";
   public static String field3903 = "Connection lost";
   public static String field3904 = "Could not complete login.";
   public static String field3905 = "Starting game engine...";
   public static String field3906 = "Please wait 1 minute and try again.";
   public static String field3907 = "Connecting to update server";
   public static String field3908;
   public static String field3909 = "Loaded update list";
   public static String field3910 = "Prepared sound engine";
   public static String field3911 = "Loading fonts - ";
   public static String field3912;
   public static String field3913 = "Loading title screen - ";
   public static String field3914;
   public static String field3915 = "Loading config - ";
   public static String field3916 = "Loaded config";
   public static String field3917 = "Loading sprites - ";
   public static String field3918;
   public static String field3919 = "Please try using a different world.";
   public static String field3920;
   public static String field3921 = "Loaded input handler";
   public static String field3922;
   public static String field3923 = "Loaded wordpack";
   public static String field3924;
   public static String field3925;
   public static String field3926 = "Loading world map - ";
   public static String field3927 = "Loaded world map";
   public static String field3929 = "Support Page";
   public static String field3930;
   public static String field3931 = "Please enter a 6-digit PIN.";
   public static String field3932 = "Checking for updates - ";
   public static String field3933;
   public static String field3934;
   public static String field3935 = " seconds.";
   public static String field3936 = "Connection timed out.";
   public static String field3937 = "Please try using a different world.";
   public static String field3938 = "Loaded interfaces";
   public static String field3939 = "";
   public static String field3940 = "Please try using a different world.";
   public static String field3941;
   public static String field3942;
   public static String field3943 = "Your profile will be transferred in:";
   public static String field3944 = "";
   public static String field3945 = "Your account has been involved";
   public static String field3946 = "in serious rule breaking.";
   public static String field3947 = "";
   public static String field3948 = "Either your account is still logged in, or the last";
   public static String field3949 = "Take";
   public static String field3950 = "Please wait - attempting to reestablish";
   public static String field3951;
   public static String field3952 = "Please reload this page.";
   public static String field3953;
   public static String field3954 = "This world is full.";
   public static String field3955 = "Please use a different world.";
   public static String field3956 = "";
   public static String field3957 = "Unable to connect.";
   public static String field3958 = "Login server offline.";
   public static String field3959 = "";
   public static String field3960;
   public static String field3961;
   public static String field3962;
   public static String field3963 = "RuneScape has been updated!";
   public static String field3964 = "Bad session id.";
   public static String field3965;
   public static String field3966;
   public static String field3967 = "Press 'change your password' on front page.";
   public static String field3968 = "";
   public static String field3969 = "You need a members account to login to this world.";
   public static String field3970 = "Please subscribe, or use a different world.";
   public static String field3971 = "";
   public static String field3972;
   public static String field3973;
   public static String field3974 = "";
   public static String field3975 = "The server is being updated.";
   public static String field3976;
   public static String field3977 = "";
   public static String field3978 = "Too many login attempts.";
   public static String field3979 = "Please wait a few minutes before trying again.";
   public static String field3980 = "";
   public static String field3981;
   public static String field3982;
   public static String field3983 = "to a non-members area.";
   public static String field3984 = "Account locked as we suspect it has been stolen.";
   public static String field3985;
   public static String field3986;
   public static String field3987 = "";
   public static String field3988;
   public static String field3989;
   public static String field3990;
   public static String field3991 = "Members object";
   public static String field3992;
   public static String field3993;
   public static String field3994;
   public static String field3995;
   public static String field3996;
   public static String field3997;
   public static String field3998;
   public static String field3999;
   public static String field4000;
   public static String field4001;
   public static String field4002 = "Please try using a different world.";
   public static String field4003;
   public static String field4004 = "Loaded sprites";
   public static String field4005;
   public static String field4006;
   public static String field4007;
   public static String field4008;
   public static String field4009;
   public static String field4010;
   public static String field4011 = "Loaded fonts";
   public static String field4012 = "Loading textures - ";
   public static String field4013;
   public static String field4014;
   public static String field4015;
   public static String field4016;
   public static String field4017;
   public static String field4018 = "members world and move your character";
   public static String field4019 = "Loading wordpack - ";
   public static String field4020;
   public static String field4021 = "Loading interfaces - ";
   public static String field4022;
   public static String field4023;
   public static String field4024;
   public static String field4025;
   public static String field4026;
   public static String field4027;
   public static String field4028;
   public static String field4029;
   public static String field4030 = "for 30 days: ";
   public static String field4031;
   public static String field4032;
   public static String field4033;
   public static String field4034;
   public static String field4035;
   public static String field4036;
   public static String field4037;
   public static String field4038;
   public static String field4039;
   public static String field4040;
   public static String field4041;
   public static String field4042;
   public static String field4043;
   public static String field4044;
   public static String field4045;
   public static String field4046;
   public static String field4047;
   public static String field4048;
   public static String field4049;
   public static String field4050;
   public static String field4051 = "Login limit exceeded.";
   public static String field4052;
   public static String field4053;
   public static String field4054;
   public static String field4055;
   public static String field4056;
   public static String field4057;
   public static String field4058;
   public static String field4059;
   public static String field4060;
   public static String field4061;
   public static String field4062;
   public static String field4063;
   public static String field4064;
   public static String field4065;
   public static String field4066;
   public static String field4067;
   public static String field4068;
   public static String field4069;
   public static String field4070 = "Loaded title screen";
   public static String field4071;
   public static String field4072;
   public static String field4073 = "To access this free world, log into a";
   public static String field4074;
   public static String field4075 = "";
   public static String field4076;
   public static String field4077;
   public static String field4078;
   public static String field4079;
   public static String field4080;
   public static String field4081;
   public static String field4082;
   public static String field4083 = "You have only just left another world.";
   public static String field4084 = "No response from server.";
   public static String field4085;
   public static String field4086;
   public static String field4087;
   public static String field4088;
   public static String field4089;
   public static String field4090;
   public static String field4091 = "Too many connections from your address.";
   public static String field4092;
   public static String field4093;
   public static String field4094;
   public static String field4095;
   public static String field4096 = "Error connecting to server.";
   public static String field4097;
   public static String field4098;
   public static String field4099;
   public static String field4100 = "Please try again later.";
   public static String field4101;
   public static String field4102;
   public static String field4103;
   public static String field4104;
   public static String field4105;
   public static String field4106;
   public static String field4107;
   public static String field4108;
   public static String field4109;
   public static String field4110;
   public static String field4111;
   public static String field4112;
   public static String field4113;
   public static String field4114;
   public static String field4115;
   public static String field4116 = "Unable to connect.";
   public static String field4117;
   public static String field4118;
   public static String field4119 = "Prepared visibility map";
   public static String field4120;
   public static String field4121;
   public static String field4122 = "";
   public static String field4123;
   public static String field4124;
   public static String field4125;
   public static String field4126;
   public static String field4127;
   public static String field4128;
   public static String field4129;
   public static String field4130;
   public static String field4131 = "Discard";
   public static String field4132;
   public static String field4133;
   public static String field4134;
   public static String field4135;
   public static String field4136;
   public static String field4137;
   public static String field4138;
   public static String field4139;
   public static String field4140;
   public static String field4141;
   public static String field4142;
   public static String field4143;
   public static String field4144;
   public static String field4145;
   public static String field4146;
   public static String field4147;
   public static String field4148;
   public static String field4149;
   public static String field4150;
   public static String field4151;
   public static String field4152;
   public static String field4153;
   public static String field4154;
   public static String field4155;
   public static String field4156;
   public static String field4157;
   public static String field4158;
   public static String field4159;
   public static String field4160;
   public static String field4161;
   public static String field4162;
   public static String field4163;
   public static String field4164;
   public static String field4165;
   public static String field4166;
   public static String field4167;
   public static String field4168 = "";
   public static String field4169;
   public static String field4170 = "";
   public static String field4171;
   public static String field4172 = "Loaded textures";
   public static String field4173;
   public static String field4174;
   public static String field4175;
   public static String field4176;
   public static String field4177;
   public static String field4178;
   public static String field4179;
   public static String field4180;
   public static String field4181 = "";
   public static String field4182;
   public static String field4183;
   public static String field4184;
   public static String field4185;
   public static String field4186;
   public static String field4187;
   public static String field4188;
   public static String field4189;
   public static String field4190;
   public static String field4191;
   public static String field4192;
   public static String field4193;
   public static String field4194 = "world you were using has become unavailable.";
   public static String field4195;
   public static String field4196;
   public static String field4197;
   public static String field4198;
   public static String field4199;
   public static String field4200;
   public static String field4201;
   public static String field4202;
   public static String field4203;
   public static String field4204;
   public static String field4205;
   public static String field4206;
   public static String field4207;
   public static String field4208;
   public static String field4209;
   public static String field4210;
   public static String field4211;
   public static String field4212 = "We suspect someone knows your password.";
   public static String field4213;
   static String field3928 = "Please visit the support page for assistance.";

   static {
      field3985 = field3928;
      field3986 = "";
      field4016 = "This world is running a closed Beta.";
      field3962 = "Sorry invited players only.";
      field3989 = "Please use a different world.";
      field3990 = "Invalid loginserver requested.";
      field4179 = "Please try using a different world.";
      field3972 = "";
      field4145 = "Malformed login packet.";
      field3994 = "Please try again.";
      field3995 = "";
      field3996 = "No reply from loginserver.";
      field3997 = "Please wait 1 minute and try again.";
      field3998 = "";
      field3999 = "Error loading your profile.";
      field4000 = "Please contact customer support.";
      field4001 = "";
      field4023 = "Unexpected loginserver response.";
      field4003 = "Please try using a different world.";
      field4209 = "";
      field4005 = "This computers address has been blocked";
      field4006 = "as it was used to break our rules.";
      field4007 = "";
      field3920 = "";
      field4009 = "Service unavailable.";
      field4141 = "";
      field3973 = "";
      field3965 = "Please enter your username/email address.";
      field3981 = "";
      field4014 = "";
      field4015 = "Please enter your password.";
      field3988 = "";
      field4017 = "Your account must have a displayname set";
      field3941 = "in order to play the game.  Please set it";
      field4164 = "via the website, or the main game.";
      field4020 = "The unpaid balance on your account needs";
      field3930 = "to be resolved before you can play.";
      field4022 = field3928;
      field4008 = "Your account is currently inaccessible.";
      field4024 = "Please try again in a few minutes.";
      field4025 = "";
      field4026 = "You need to vote to play!";
      field4027 = "Visit runescape.com and vote,";
      field4127 = "and then come back here!";
      field4117 = "Sorry, but your account is not eligible to play.";
      field4110 = "For more information, please take a look at";
      field4031 = "our privacy policy.";
      field4032 = "Privacy Policy";
      field4161 = "Enter the 6-digit code generated by your";
      field4034 = "authenticator app.";
      field3976 = "";
      field4085 = "The code you entered was incorrect.";
      field4191 = "Please try again.";
      field4038 = "";
      field4086 = "Login attempt timed out.";
      field4040 = "Please try again.";
      field4041 = "";
      field4042 = "You were signed out.";
      field4043 = "Please sign in again.";
      field4044 = "";
      field4045 = "Failed to login.";
      field4046 = "Please try again.";
      field4047 = "";
      field4048 = "Unexpected server response";
      field4049 = "Please try using a different world.";
      field4137 = "";
      field3942 = " has logged in.";
      field4052 = " has logged out.";
      field4053 = "Unable to find ";
      field3898 = "Use";
      field4182 = "Examine";
      field4056 = "Attack";
      field4057 = "Choose Option";
      field4058 = " more options";
      field4029 = "Walk here";
      field4060 = "level-";
      field4061 = "skill-";
      field4062 = "Please wait...";
      field4063 = "Close";
      field4064 = " ";
      field4065 = "M";
      field4066 = "M";
      field4067 = "K";
      field4068 = "K";
      field4069 = "World";
      field4035 = "Your friend list is full. Max of 200 for free users, and 400 for members";
      field4071 = " is already on your friend list";
      field4072 = "Your ignore list is full. Max of 100 for free users, and 400 for members";
      field4080 = " is already on your ignore list";
      field3924 = "You can't add yourself to your own friend list";
      field4177 = "You can't add yourself to your own ignore list";
      field4076 = "Please remove ";
      field4077 = " from your ignore list first";
      field4078 = "Please remove ";
      field4079 = " from your friend list first";
      field3953 = "yellow:";
      field4081 = "yellow:";
      field4082 = "red:";
      field4190 = "red:";
      field3901 = "green:";
      field4140 = "green:";
      field4133 = "cyan:";
      field4087 = "cyan:";
      field4088 = "purple:";
      field4089 = "purple:";
      field4090 = "white:";
      field4174 = "white:";
      field4092 = "flash1:";
      field4037 = "flash1:";
      field4094 = "flash2:";
      field4095 = "flash2:";
      field4176 = "flash3:";
      field4097 = "flash3:";
      field4098 = "glow1:";
      field4099 = "glow1:";
      field3966 = "glow2:";
      field4101 = "glow2:";
      field4102 = "glow3:";
      field4103 = "glow3:";
      field4104 = "wave:";
      field4105 = "wave:";
      field4106 = "wave2:";
      field3951 = "wave2:";
      field4108 = "shake:";
      field4109 = "shake:";
      field4187 = "scroll:";
      field3982 = "scroll:";
      field4112 = "slide:";
      field4113 = "slide:";
      field4114 = "RuneScape is loading - please wait...";
      field4115 = "";
      field4192 = "Enter your username/email & password.";
      field4111 = "";
      field4118 = "Warning!";
      field4039 = "This is a <col=ff0000>PvP<col=ffffff> world.";
      field4120 = "Players can attack each other";
      field4121 = "almost everywhere.";
      field4107 = "This is a <col=ffff00>High Risk<col=ffffff> world.";
      field3922 = "The Protect Item prayer will";
      field4124 = "not work on this world.";
      field4125 = "This is a <col=ffff00>High Risk <col=ff0000>PvP<col=ffffff> world.";
      field4203 = "Players can attack each other almost everywhere";
      field4033 = "and the Protect Item prayer won't work.";
      field4128 = "This is a <col=00ffff>Beta<col=ffffff> world.";
      field4129 = "Your normal account will not be affected.";
      field4130 = "";
      field4205 = "Authenticator";
      field4132 = "<u=ff>Can't Log In?</u>";
      field4074 = "";
      field4134 = "Connecting to server...";
      field4135 = "";
      field4136 = "The game servers are currently being updated.";
      field4154 = "Please wait a few minutes and try again.";
      field4138 = "";
      field4139 = "";
      field4055 = "You were disconnected from the server.";
      field4193 = "";
      field4142 = "Login: ";
      field4143 = "Password: ";
      field4144 = "PIN: ";
      field3934 = "Welcome to RuneScape";
      field4146 = "New User";
      field4147 = "Existing User";
      field4148 = "Login";
      field4149 = "Cancel";
      field4150 = "Remember username";
      field4151 = "Hide username";
      field4152 = "Invalid credentials.";
      field4198 = "For accounts created after 24th November 2010, please use your";
      field3908 = "email address to login. Otherwise please login with your username.";
      field4155 = "Try again";
      field4036 = "Forgotten password?";
      field4157 = "Forgotten your password?";
      field4158 = "Username/email: ";
      field4159 = "Recover";
      field4160 = "Back";
      field4093 = "Can't login? Click here.";
      field3892 = "Still having trouble logging in?";
      field4163 = "Having trouble logging in?";
      field4153 = "";
      field4165 = "Page has opened in a new window.";
      field4166 = "(Please check your popup blocker.)";
      field4167 = "Please enter your username.";
      field4010 = "If you created your account after November";
      field4169 = "2010, this will be the creation email address.";
      field4050 = field4153;
      field4171 = field4165;
      field4183 = field4166;
      field4173 = "";
      field4162 = "Error connecting to server.";
      field4175 = "";
      field4204 = "The part of the website you are trying";
      field4156 = "to connect to is offline at the moment.";
      field4123 = "Please try again later.";
      field3914 = "Sorry, there was an error trying to";
      field4180 = "log you in to this part of the website.";
      field4184 = "Please try again later.";
      field4178 = "";
      field3933 = "Error connecting to server.";
      field3992 = "";
      field4185 = "You must enter a valid login to proceed. For accounts";
      field4186 = "created after 24th November 2010, please use your";
      field3912 = "email address. Otherwise please use your username.";
      field4188 = "Your date of birth isn't set.";
      field4189 = "Please verify your account status by";
      field4208 = "setting your date of birth.";
      field4211 = "Set Date of Birth";
      field3960 = "Your date of birth information is waiting";
      field4028 = "to be reviewed by our staff.";
      field3918 = "It will be processed shortly.";
      field4195 = "Before using this app, please read and accept our";
      field4196 = "<col=ffd200>terms of use</col>, <col=ffd200>privacy policy</col>, and <col=ffd200>end user licence</col>";
      field4197 = "<col=ffd200>agreement (EULA)</col>.";
      field4013 = "By accepting, you agree to these documents.";
      field4199 = "You must accept our terms of use, privacy policy,";
      field4200 = "and end user licence agreement to continue.";
      field4201 = "Accept";
      field3993 = "Decline";
      field4054 = "Select a world";
      field4126 = "Members only world";
      field4059 = "Free world";
      field4206 = "World";
      field4207 = "Players";
      field3925 = "Location";
      field4202 = "Type";
      field4210 = "OFF";
      field3891 = "FULL";
      field3961 = "Loading...";
      field4213 = "Click to switch";
   }

   class338() throws Throwable {
      throw new Error();
   }
}
