name: RSBox (push)
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v3
      - name: Setup gradlew executable
        run: chmod +x ./gradlew
      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 11
          cache: 'gradle'
      - name: Gradle 'build'
        run: ./gradlew build